apiVersion: harness.io/v1
kind: Workflow
type: workflow
identifier: e2e_react_app_provisioning_workflow
name: E2E React App Provisioning
owner: user:account/todd.parson@harness.io
orgIdentifier: sandbox
projectIdentifier: parson
spec:
  output:
    links:
    - title: Pipeline Details
      url: ${{ steps.trigger.output.PipelineUrl }}
  lifecycle: sandbox
  parameters:
    - title: App Basics
      required:
      - project_name
      - project_owner
      properties:
        project_name:
          title: Project Name
          type: string
          description: Human-readable name (e.g., “My Cool App”).
        project_owner:
          title: Project Owner (email or team)
          type: string
          default: todd.parson@harness.io
        project_description:
          title: Project Description
          type: string
          default: Testing for POC
    - title: Repository & Branching
      required:
      - gh_org
      - base_repo
      - base_branch
      - new_branch_prefix
      properties:
        gh_org:
          title: GitHub Org
          type: string
          default: harness-idp-sandbox
        base_repo:
          title: Base Repo (monorepo)
          type: string
          default: monorepo-idp-example
        base_branch:
          title: Base Branch
          type: string
          default: main
        new_branch_prefix:
          title: New Branch Prefix
          type: string
          default: feature
    - title: Environment & Region
      required:
      - environment_name
      - aws_region
      properties:
        environment_name:
          title: Environment Name
          type: string
          enum:
          - dev
          - qa
          - prod
          default: dev
        aws_region:
          title: AWS Region
          type: string
          default: us-east-1
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
  - id: trigger
    name: Provision React App (run pipeline)
    action: trigger:harness-custom-pipeline
    input:
      url:
      - https://app.harness.io/ng/#/account/<YOUR_ACCOUNT_ID>/orgs/sandbox/projects/parson/pipelines/E2E_React_App_Provisioning/executions
      apikey: ${{ parameters.token }}
      inputset:
        project_name: ${{ parameters.project_name }}
        project_owner: ${{ parameters.project_owner }}
        project_description: ${{ parameters.project_description }}
        gh_org: ${{ parameters.gh_org }}
        base_branch: ${{ parameters.base_branch }}
        base_repo: ${{ parameters.base_repo }}
        new_branch_prefix: ${{ parameters.new_branch_prefix }}
        environment_name: ${{ parameters.environment_name }}
        aws_region: ${{ parameters.aws_region }}
metadata:
  description: |
    Scaffolds a new React app into the monorepo via Cookiecutter, creates a feature branch, commits the scaffolded code, and opens a PR using the E2E_React_App_Provisioning pipeline.
